### ISSUE TITLE
Docs used on www.mozilla.org using unsupported language code

### ISSUE THREAD

**Issue by pmac** [mozilla/legal-docs#1155]
On bedrock (www.m.o) we use the `hi-IN` locale, but the docs in here that we use are named just `hi`. This seems to be causing some confusion on the site. For example the Firefox privacy notice:

https://www.mozilla.org/en-US/privacy/firefox/

In the footer of that page is a dropdown with all available languages. `hi` appears in that list, but it doesn't work and redirects to en-US because `hi` isn't an active language for the site. Manually going to `hi-IN` also doesn't work since the doc doesn't include a filename with that locale code. I think the solution is to rename `hi.md` files to `hi-IN.md` files.

Is this the right way to go in your opinion @peiying2?

**Comment by pmac** [comment]
Similarly there are `sw.md` files in this repo for those policies but `sw` isn't a language code that the site supports either. So "Swahili" does show up in the list of available languages for the pages but it doesn't actually work. Not sure what the correct path is here unless we can enable `sw` on the site.

For reference the [full list of supported locale codes](https://github.com/mozilla/bedrock/blob/42fee04d35df125fff6da19d4c133aa1142a6653/bedrock/settings/base.py#L116-L129) is here.

**Comment by peiying2** [comment]
@pmac wow, glad we had this audit or we would have not discovered the mess. In Pontoon, it is all "hi". I think when we had two tools (Pootle and Pontoon), we may have had hi and that's how it started. Let's change it to hi-IN then. 

As for Swahili, it started as a partner request and the locale was never officially launched as far as I know. And the community was never formalized to a size that contributed to a product. We can disable it all together.

**Comment by peiying2** [comment]
Additionally, there is another locale `tl-PH`, which may have not officially used during Firefox OS days. We can keep the file, but let's change it to `tl` instead. We now have Rocket legal docs using `tl` which is in agreement with what's in Pontoon.

**Comment by pmac** [comment]
It's potentially even more confusing since there are files for both `hi` and `hi-IN` in the [bedrock l10n files](https://github.com/mozilla-l10n/bedrock-l10n). If we need to switch bedrock to `hi` to be inline with other mozillian projects then I don't think that would be difficult either. What do you think?

**Comment by pmac** [comment]
Also, shall I submit a PR here for these changes or are you planning to do it? Either way is fine with me, just don't want to duplicate effort.

**Comment by peiying2** [comment]
Please go ahead with the updates and submit a PR. I didn't know `hi` and `hi-IN` are mixed in bedrock l10n files. I wonder what is in `hi` these days or if they are obsolete files and already have the hi-IN versions.

**Comment by pmac** [comment]
> I wonder what is in hi these days or if they are obsolete files and already have the hi-IN versions.

I wondered the same thing. Haven't gotten a chance to investigate fully yet. They're certainly not being used by the site at present though.

**Comment by pmac** [comment]
According to the [git repo for translators](https://github.com/mozilla-l10n/www.mozilla.org/tree/master/hi) the `hi` directory hasn't seen an update in around 4 years. So I think it's dead and can probably be removed.

**Comment by quyww** [comment]
#5775 fix #5987
