### ISSUE TITLE
Need to update ScreenshotGo legal docs

### ISSUE THREAD

**Issue by weslyhuang** [mozilla/legal-docs#1175]
with the latest version in Gdoc[1], we need to update the ScreenshotGo legal docs [2] (both en-us and id version) to make them aligned.

@peiying2 , would you help on this? Thanks!

[1] https://docs.google.com/document/d/1QMnw09YXCIHLlo-BtFiJ7S5YvdlX6Uz2UJuKE1I3ovE/edit
[2] https://github.com/mozilla/legal-docs/tree/master/firefox_screenshotgo_about_rights

**Comment by peiying2** [comment]
@weslyhuang is this the link I should use: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/index.html?

**Comment by weslyhuang** [comment]
@peiying2 sorry I didn't follow the question. I thought all we need to do is update the content of the github md files (both en-us, and the l10n-ed id versions) [1] according to the Legal GoogleDoc [2]. I'm not sure where we should place the link of the telemetry doc you posted?

[1] https://github.com/mozilla/legal-docs/tree/master/firefox_screenshotgo_about_rights
[2] https://docs.google.com/document/d/1QMnw09YXCIHLlo-BtFiJ7S5YvdlX6Uz2UJuKE1I3ovE/edit

**Comment by peiying2** [comment]
@weslyhuang let me know if this still needs to be done, otherwise, we can close it. Going through the long standing issues, and came across this one.

**Comment by weslyhuang** [comment]
Thanks for asking this, @peiying2! And yes I believe we should (and fine with a lower priority). Indeed we have quite less activities on ScreenshotGo and the team in Taipei is focusing on FirefoxLite nowadays. Yet the App is still alive on GooglePlay store that available for users (and I keep receiving few review comments every day) so I believe it will be better we can complete the piece when you have time. Thanks!

**Comment by peiying2** [comment]
This request is no longer needed.
