### ISSUE TITLE
Typo in French legal page chiffrés vs cryptés

### ISSUE THREAD

**Issue by pdehaan** [mozilla/legal-docs#1243]
Per https://github.com/mozilla/send/issues/1253

> Legal page doesn't seem to be taken from this git repo. But anyway:
>
> in Mozilla Send repo, the right French translation is used (files are "chiffrés", not "cryptés"):
>
>> ./public/locales/fr/send.ftl:introDescription = { -send-brand } vous permet de partager des fichiers **chiffrés** (...)
>> ./public/locales/fr/send.ftl:notifyUploadEncryptDone = Votre fichier est **chiffré** (...)
>
> On legal page https://www.mozilla.org/fr/about/legal/terms/services/#send
>
>> (e) Firefox Send vous permet de partager des fichiers **cryptés**

---

In https://github.com/mozilla/send/issues/1253#issuecomment-473373802, @TheoChevalier adds:

> I can confirm “cryptés” is a blatant mistake and that the latest update in the legal-docs repo needs improvements. Right now it’s not adhering to the styleguide, nor using the UI terminology. I can offer some review next week and file an issue upstream

**Comment by peiying2** [comment]
I have made the change in the repo. The update will be grouped with the next legal doc production push.
