### ISSUE TITLE
Create a single bn (Bengali) version

### ISSUE THREAD

**Issue by peiying2** [mozilla/legal-docs#1248]
@pmac the two Bengali communities (bn-BG, bn-IN) have agreed to combine effort to localized all products and webpages into a single Bengali version. Legal documentations is part of this effort. It is a blocker for the mozilla.org merge as well.

Currently, the two versions in the repo share the same content. We should create a bn folder for any docs we have one or both locales represented. After it is set up, we wait for mozilla.org to be ready and push of both them to production at the same time.

**Comment by peiying2** [comment]
@flodolo progress is tracked here: https://github.com/mozilla-l10n/pm-projects/issues/161

**Comment by pmac** [comment]
What exactly does bedrock need to do for this? Should it also remove `bn-BG` and `bn-IN` from the `PROD_LANGUAGES` setting and add `bn`? Or should `bn` be added to the list and keep the other two? If the former then we'll need to coordinate adding a `bn` folder to the locales repo for strings as well as the `bn.md` files to this repo.

**Comment by peiying2** [comment]
After we have established `bn`, we can remove `bn-IN` and `bn-BG`. We can make the change at the same time or after showing `bn` working properly.

**Comment by flodolo** [comment]
1. The idea is to create bn on the legal-docs and push it to production
2. Create bn in mozilla.org repo and tools
3. Add bn to Bedrock, push it to production

Once this is done, we can clean up bn-IN and bn-BD in any order.

**Comment by pmac** [comment]
Sounds good to me. This issue is currently assigned to me. What part of the above would you like for me to work on?

**Comment by flodolo** [comment]
1 for sure, possibly 3 because I feel there are redirects in place somewhere in the code (and maybe related tests), and it's not just about adding bn to PROD_LOCALES.

2 is completely on me, and I can start as soon as the changes to legal-docs are in prod.

**Comment by pmac** [comment]
The way bedrock currently works for legal-docs is that a doc will be available in a language if a file with that locale ID exists and the locale is in the `PROD_LANGUAGES` setting. So we can go ahead and create the `bn.md` files now and they'll be available when we add `bn` to the prod languages and the others will be removed when we remove them from the setting. I don't think there are any other special redirects, so we'll just need the `bn` folder to exist in the locales repo and we can then do the switch. So I can go ahead with 1) and Flod can go ahead with 2) and we can do 3) after both of those are done. Then we can 4) clean up the now unused `bn-IN` and `bn-BD` files and directories.

**Comment by flodolo** [comment]
> I don't think there are any other special redirects,

For some reason I thought there was a redirected from /bn (relic from Firefox OS), like for /es to /es-ES, but it's not there.

**Comment by pmac** [comment]
Hmm... Let me look some more to be sure.

**Comment by pmac** [comment]
I did a quick check and not all of the `bn-IN.md` and `bn-BD.md` files are identical for the same document. Any idea which should become `bn.md` in those cases?

```shell
$ find . -name bn-BD.md -or -name bn-IN.md | xargs md5sum
a71c7c2f32edd2799589aa08b774cba7  ./WebRTC_ToS/bn-BD.md
a71c7c2f32edd2799589aa08b774cba7  ./WebRTC_ToS/bn-IN.md
3acf44f06381cfac200dd67156f12541  ./Websites_ToU/bn-BD.md
dd31a265d450f55e15ff1af9b97f3aca  ./Websites_ToU/bn-IN.md
537291edefa1564e827bbb8bbbd06f5e  ./firefox_os_privacy_notice/bn-BD.md
52a7fb905e9f8c52ba69a94b491f6275  ./firefox_os_privacy_notice/bn-IN.md
728c0cc9d70be34c1f6f97be331145a6  ./marketplace_privacy_policy/bn-BD.md
728c0cc9d70be34c1f6f97be331145a6  ./marketplace_privacy_policy/bn-IN.md
efbb44977ca4713949e98a3b7db1b69e  ./acceptable_use_policy/bn-BD.md
efbb44977ca4713949e98a3b7db1b69e  ./acceptable_use_policy/bn-IN.md
fafb4f9387cc6f0a5faeac801af38925  ./firefox_privacy_notice/bn-BD.md
c3baa2089b3a07cb3c2cd0e4cc995b36  ./firefox_privacy_notice/bn-IN.md
1df4a83a96659ef52fa6cec4ec1bd13c  ./marketplace_developer_agreement/bn-BD.md
feefbad0ff5fbb9231800b7c527a6172  ./marketplace_developer_agreement/bn-IN.md
0f832ab6f83b829383320dec12ab2f3b  ./WebRTC_PrivacyNotice/bn-BD.md
ead146ae36a4fa5177c169bde98ffdfe  ./WebRTC_PrivacyNotice/bn-IN.md
75167ea71a82b719568015ee7341cb23  ./firefox_cloud_services_ToS/bn-BD.md
75167ea71a82b719568015ee7341cb23  ./firefox_cloud_services_ToS/bn-IN.md
7b33d3a985e59e0aac8473eb37c4bca0  ./mozilla_privacy_policy/bn-BD.md
7b33d3a985e59e0aac8473eb37c4bca0  ./mozilla_privacy_policy/bn-IN.md
d5f0a71ca7d2d9eb3234d012850e29dc  ./marketplace_terms_of_use/bn-BD.md
d5f0a71ca7d2d9eb3234d012850e29dc  ./marketplace_terms_of_use/bn-IN.md
a8e2b316be750ee93b8cb4ee5a5abac4  ./websites_privacy_notice/bn-BD.md
7f2e6134b5a9e728f2dac1b628a27638  ./websites_privacy_notice/bn-IN.md
884f804a2ccecad029e4a7af463612db  ./firefox_cloud_services_PrivacyNotice/bn-BD.md
884f804a2ccecad029e4a7af463612db  ./firefox_cloud_services_PrivacyNotice/bn-IN.md
```

**Comment by pmac** [comment]
If it helps these are the ones that differ:

* Websites_ToU
* firefox_os_privacy_notice
* firefox_privacy_notice
* marketplace_developer_agreement
* WebRTC_PrivacyNotice
* websites_privacy_notice

**Comment by peiying2** [comment]
Thanks for creating the diff list. We can remove these two docs as they have EOLed and have expired even the end of the EOL period.
*firefox_os_privacy_notice
*marketplace_developer_agreement 

Let me check the others.

**Comment by peiying2** [comment]
The updated files have been delivered. We have the following four files to consolidate as bn:
* firefox_privacy_notice
* websites_privacy_notice

Let's pick bn-BD as source of `bn` for all the docs.

**Comment by peiying2** [comment]
We can stop converting the following docs:
* /firefox_os_privacy_notice
* /marketplace_privacy_policy
* /marketplace_terms_of_use
* /marketplace_developer_agreement

**Comment by pmac** [comment]
Looks like marketplace is down entirely, so that one can be deleted it looks like, but firefox_os_privacy_notice is still in use on www.m.o, so we'll need to at least leave it alone until that page is removed from the site.

https://www.mozilla.org/en-US/privacy/firefox-os/
