### ISSUE TITLE
Reward link points to site in Indonesian

### ISSUE THREAD

**Issue by peiying2** [mozilla/legal-docs#1400]
@chianger the legal doc for https://github.com/mozilla/legal-docs/pull/1384 points to Indonesian site, even though the doc is in non-id languages. Do you have other URLs we can use? This is not going to be good user experience. 

I have a series of legal docs to update. I will merge them but the link needs to be updated unless it is intended to be in Indonesian.

**Comment by chianger** [comment]
We are going to launch that campaign in Indonesia only so the vendor (Shopee) only creates the Indonesian site for this time. We are aware of this , and yes that does reminds us to reconsider going forward how we are going to maintain the page. For now it seems we have to update the link each time when we plan a new campaign. @peiying2

**Comment by peiying2** [comment]
This is no longer relevant.
