### ISSUE TITLE
Add Japanese "Legal Terms" page

### ISSUE THREAD

**Issue by marsf** [mozilla/legal-docs#1422]
Currently, the [Common Voice Legal Terms page in Japanese](https://voice.mozilla.org/ja/terms) is blank. Because of lacks the file https://github.com/mozilla/legal-docs/tree/master/Common_Voice_Terms/ja.md

If there is no translation, it is acceptable that shown in English temporally.

**Comment by peiying2** [comment]
@marsf thank you for raising this issue. Common Voice team updates the locale list for legal docs every so often. Your issue reminds me to check the current standing of locales reaching major milestones. Japanese is one of the locales to do so since our last update of the locale list. I will make sure Japanese in our next round.

**Comment by marsf** [comment]
@peiying2 Any progress?
If there is no translation, please just copy "en.md" to ja.md. 
IMO, it's critical to contribute their voices for Common Voice.

**Comment by peiying2** [comment]
> @peiying2 Any progress?
> If there is no translation, please just copy "en.md" to ja.md.
> IMO, it's critical to donate their voices for Common Voice.

Good timing, the vendor will deliver Japanese and 16 other languages by next Monday. I welcome you to take a review and make necessary edits if you see necessary. I do need another person to review your changes (if you make any) before I can merge the revision to master. I will comment here once the localized version is available. I have not forgotten this.

**Comment by marsf** [comment]
Thank you, I will check it.

**Comment by peiying2** [comment]
@marsf the two documents are in lego repo. Push to production is pending CV team's push schedule:
- https://github.com/mozilla/legal-docs/blob/master/Common_Voice_Privacy_Notice/ja.md
- https://github.com/mozilla/legal-docs/blob/master/Common_Voice_Terms/ja.md

**Comment by peiying2** [comment]
Feel free to make changes and invite another contributor to review before I merge the change.
