### ISSUE TITLE
Anchor ids should be explicitly defined in privacy notice

### ISSUE THREAD

**Issue by l-hedgehog** [mozilla/legal-docs#1426]
Instead of being ["derived from the text of the header"](https://python-markdown.github.io/extensions/toc/#custom-labels), which is not stable across different locales.

Without it defined,
https://www.mozilla.org/en-US/privacy/firefox/#suggest-relevant-content works,
https://www.mozilla.org/de/privacy/firefox/#suggest-relevant-content doesn't, it's actually
https://www.mozilla.org/de/privacy/firefox/#vorschlag-relevanter-inhalte

As a result, [this link](https://searchfox.org/mozilla-central/rev/7fba7adfcd69/browser/components/newtab/lib/SectionsManager.jsm#66-67) in Fx doesn't work for languages other than English.

With it defined, both
https://www.mozilla.org/en-US/privacy/firefox/#defaultsearch and
https://www.mozilla.org/de/privacy/firefox/#defaultsearch works fine.

**Comment by peiying2** [comment]
This should have been fixed now. The problem was introduced when changes made to en-US, the docs were updated without a PR and were merged directly to the master branch thus l10n fell through the cracks. We have scripts in place to capture the updates in en-US now.
