### ISSUE TITLE
Update Screenshots and DNS sections of Privacy Notice

### ISSUE THREAD

**Issue by mafeld** [mozilla/legal-docs#1428]
@pmac and Eric Renaud - I've merged updates to en-US Privacy Notice for Screenshots and the DNS resolver. Can we push those updates to production?

Issue #1427

**Comment by pmac** [comment]
Is this an emergency push? If not we'll definitely get it out on Monday.

**Comment by mafeld** [comment]
not an emergency. Monday is fine.

**Comment by pmac** [comment]
The update is merged. Should be in production later today.
