### ISSUE TITLE
Push New Changes 

### ISSUE THREAD

**Issue by mafeld** [mozilla/legal-docs#1471]
@pmac - I updated the Firefox Privacy Notice to fix a broken link and add a new DNS resolver. 

Could you please push this to bedrock. It's not urgent, so tomorrow or Thursday would be fine. 

Here's the commit: https://github.com/mozilla/legal-docs/commit/e257eb83cf2fba359bf6d5e134500a4ff845be5e

**Comment by pmac** [comment]
I also just merged #1469 so I'll pull that in as well.

**Comment by peiying2** [comment]
If the link is broken, I wonder whether we should update the localized version. But the date change has to wait.
