### ISSUE TITLE
Push VPN TOS update to Bedrock on April 14

### ISSUE THREAD

**Issue by mafeld** [mozilla/legal-docs#1568]
@pmac - Can we please push these updated terms to Bedrock on April 14? - https://github.com/mozilla/legal-docs/pull/1567/commits/a52d8494cd5b3f6ab8397d92bc66726b28861012

@peiying2 - FYI

**Comment by pmac** [comment]
Sure. I'll set a reminder for this.

**Comment by peiying2** [comment]
The files are delivered: https://bugzilla.mozilla.org/show_bug.cgi?id=1694453

**Comment by mafeld** [comment]
Hi all - update on this: The team has pushed launch back to April 28, so we should push live on the 28th instead of the 14th. 
Also, I've made a few additional minor changes, so the updated commit is: https://github.com/mozilla/legal-docs/commit/8814f535b3c83dee6cc0d1868baaba67cbe36d75
(I'll reopen the localization bug for the new lines).

**Comment by mafeld** [comment]
@pmac - Can you confirm that you will push this live tomorrow with the VPN launch??
https://github.com/mozilla/legal-docs/commit/8814f535b3c83dee6cc0d1868baaba67cbe36d75

Localization bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1694453

**Comment by pmac** [comment]
Yup. I've got it on my reminders. Sorry, I thought I'd responded to your last message. My apologies for failing to acknowledge.

**Comment by litkaemily** [comment]
Hi @pmac we'll also need to push the privacy notice updates live tomorrow (commits: 91a7e48bf8d830efa8acf024fad3772d454c86f2, 207b4cc5e459e07a078b4e0c97c98ce1a51e9f35, and ac2dd104b807ecaeff3bdcd7f8b7f2741d645e7b)

Thanks!

**Comment by pmac** [comment]
Cool. Looks like I can just move everything in the `master` branch to `prod`.

**Comment by pmac** [comment]
Done
