### ISSUE TITLE
Android data docs link is out of date

### ISSUE THREAD

**Issue by chutten** [mozilla/legal-docs#1590]
The link to the Android data documentation points at https://firefox-source-docs.mozilla.org/mobile/android/index.html which is the old version of Firefox for Android. 

Instead it should point to something more current. Like perhaps the Glean Dictionary: https://dictionary.telemetry.mozilla.org/

**Comment by peiying2** [comment]
@litkaemily @mafeld could you comment on this issue?

**Comment by litkaemily** [comment]
Hi @chutten thanks for spotting this. Can you point me to where in the privacy notice this link is? Thanks!

**Comment by chutten** [comment]
That'd be in the section "Improve performance and stability for users everywhere"

**Comment by litkaemily** [comment]
Great, I see now. Who owns this? I.e., who should review if the glean link is the best one? Happy to run it down. Thank you !!

**Comment by chutten** [comment]
That's a good question, @litkaemily. I'm not sure who exactly. Perhaps someone from Fenix Product, or maybe Dan McKinley from the Data org?

**Comment by flodolo** [comment]
I think this was fixed, as I see a link to https://dictionary.telemetry.mozilla.org/apps/fenix
