### ISSUE TITLE
Redirected en-US link in Firefox PN

### ISSUE THREAD

**Issue by flodolo** [mozilla/legal-docs#1674]
CC @mafeld @litkaemily 

[This commit](https://github.com/mozilla/legal-docs/commit/3ce235c9346d1c600e4ec980edbc02188b5c3638) recently added a link: `https://support.mozilla.org/en-US/kb/navigate-web-faster-firefox-suggest?as=u&utm_source=inproduc`. It's used 3 times as-is, and a 4th with the anchor `#w_who-are-mozillas-partners`.

There are a few issues with this link:
* It includes `en-US`, which will lead all localized versions of the PN to the English page.
* On SUMO, it already redirects to another URL: `https://support.mozilla.org/en-US/kb/firefox-suggest?as=u&utm_source=inproduc&redirectslug=navigate-web-faster-firefox-suggest&redirectlocale=en-US`
* Links to anchors don't really work great on SUMO, as the URL can be redirected to another language, but the anchor won't exist (e.g. in Italian it's `#w_chi-sono-i-partner-pubblicitari-di-mozilla`).
* I'm not sure if `inproduc` is a typo in the attribution parameters (missing `t` at the end), or if it's wanted.

If the latter is not an issue, we should update the link to `https://support.mozilla.org/kb/firefox-suggest?as=u&utm_source=inproduc`, and accept that the anchor won't work as expected.

Thoughts?

**Comment by mafeld** [comment]
I agree with all your recommendations. Thanks.
