### ISSUE TITLE
Fix Better Web 404

### ISSUE THREAD

**Issue by flodolo** [mozilla/legal-docs#1676]
From @pmac 

> The website still does link to Better Web, but the page is a 404 now due to the file removal https://www.mozilla.org/en-US/about/legal/

I see a Better Web document under /privacy
https://www.mozilla.org/en-US/privacy/betterweb/

Which comes from here
https://github.com/mozilla/legal-docs/blob/master/en/better_web_privacy.md

The one that I've removed is `better_web_terms.md`.
https://github.com/mozilla/legal-docs/blob/2b6f597c893cc7e32abc87a4bbb38122c9c22d94/en/better_web_terms.md

Should that also be removed, and links fixed on Bedrock's side?

**Comment by mafeld** [comment]
The website (https://www.mozilla.org/en-US/about/legal/) should not link to betterweb. 
Does anyone have the github link for that page so we can update it?

All betterweb notices can be archived.

**Comment by flodolo** [comment]
My guess would be https://github.com/mozilla/bedrock/blob/master/bedrock/legal/templates/legal/index.html#L62

But I haven't looked at Bedrock in a very long time, and there might more (e.g. remove the definition of `legal.terms.betterweb`).

Is it correct for Better Web to be linked in /privacy though?

**Comment by pmac** [comment]
I'll file a separate issue for removal of the better web terms items on the site.

**Comment by pmac** [comment]
Should we redirect that terms link somewhere, or just let it 404?

**Comment by mafeld** [comment]
Just let it 404.

**Comment by peiying2** [comment]
Looks like the issue is addressed.
