### ISSUE TITLE
Push new Terms and Privacy Notice live

### ISSUE THREAD

**Issue by mafeld** [mozilla/legal-docs#1715]
Hey @pmac (FYI @peiying2)
When we launch MDN Plus on March 23, could you also push the following live, which I believe have updates in Github that are not yet live on the websites:

[firefox_relay_privacy_notice.md](https://github.com/mozilla/legal-docs/blob/master/en/firefox_relay_privacy_notice.md)
[firefox_relay_tos.md](https://github.com/mozilla/legal-docs/blob/master/en/firefox_relay_tos.md)
[firefox_privacy_notice.md](https://github.com/mozilla/legal-docs/blob/master/en/firefox_privacy_notice.md)
[mdn_plus_terms.md](https://github.com/mozilla/legal-docs/blob/master/en/mdn_plus_terms.md)
[mdn_plus_privacy.md](https://github.com/mozilla/legal-docs/blob/master/en/mdn_plus_privacy.md)
[websites_privacy_notice.md](https://github.com/mozilla/legal-docs/blob/master/en/websites_privacy_notice.md) (as of posting this note, we haven't yet merged the update)

**Comment by peiying2** [comment]
@mafeld I believe these two have been pushed to production: 
1.  [firefox_relay_privacy_notice.md](https://github.com/mozilla/legal-docs/blob/master/en/firefox_relay_privacy_notice.md)
2. [firefox_relay_tos.md](https://github.com/mozilla/legal-docs/blob/master/en/firefox_relay_tos.md) 

Pending l10n update: 
[websites_privacy_notice.md](https://github.com/mozilla/legal-docs/blob/master/en/websites_privacy_notice.md) (as of posting this note, we haven't yet merged the update) - Please file a Jira issue for this. 

Ready for production push on March 23
1. [firefox_privacy_notice.md](https://github.com/mozilla/legal-docs/blob/master/en/firefox_privacy_notice.md)
2. [mdn_plus_terms.md](https://github.com/mozilla/legal-docs/blob/master/en/mdn_plus_terms.md)
3. [mdn_plus_privacy.md](https://github.com/mozilla/legal-docs/blob/master/en/mdn_plus_privacy.md)
4.

**Comment by mafeld** [comment]
Thanks @peiying2 - 

I am in the process of filing the JIRA ticket for the websites notice now. 

I don't think the relay notice or tos have been pushed to production because the website does not show the up-to-date versions.

**Comment by peiying2** [comment]
> Thanks @peiying2 -
> 
> I am in the process of filing the JIRA ticket for the websites notice now.
> 
> I don't think the relay notice or tos have been pushed to production because the website does not show the up-to-date versions.

Good to know. The current cherry-picking production push has had some issues. Let's make the push on March 23 with all you listed above. When Website PN l10n is back, we can make another push. Thanks.

**Comment by pmac** [comment]
I've set a reminder for myself to push these documents to prod the morning of Wed. the 23rd.

**Comment by pmac** [comment]
I've pushed the changes requested to production in 9f815312aeb85cd301140a6c900e2234ad13caf5. Should be live on the website within 20 minutes.
