### ISSUE TITLE
Potential New Way of Moving Documents to Production Website

### ISSUE THREAD

**Issue by pmac** [mozilla/legal-docs#1717]
## State Of Things Today

We have to move documents between git branches. The `master` branch is for documents in development, and the `prod` branch is for documents that should be displayed on our websites (specifically www.mozilla.org). This is a fine system for people very familiar with git, but for those who don't normally use git for their day-to-day work (i.e. most of the folks working with these documents) it can get confusing very quickly. Therefore we're in a state where the editors of these documents can update them themselves, but can't publish them without help from myself or others on my team.

## Proposal

I am thinking it might be easier if we keep both documents in development and for production in the default branch (`master`), but in separate directories. This would make "publishing" a document as easy as dragging it into the right place in the directory structure and commiting and pushing that change.

I'm curious if this sounds like it would be a superior solution and whether it would really enable full self-service. 

I'm thinking the directory structure could be something like what follows:

```
/
    /in-progress
        /de
           firefox-privacy.md
        /en
            firefox-privacy.md
    /published
        /de
           firefox-privacy.md
        /en
            firefox-privacy.md
```

@flodolo @peiying2

**Comment by flodolo** [comment]
I wish I had a better alternative to propose, but I haven't found one yet.

I don't think this improves the situation:
* It has the same defect of the current solution, i.e. it's not easy to see what's in production compared to stage.
* Potentially, we're talking about moving around a lot of files. That's relatively easy for me and you to script, not so much for non technical folks (manual, error prone).
* While it removes branches from the picture, it also can't be managed directly on GitHub anymore (like, ideally, it would be for the merge branch process). You need to clone locally, create branches, pull requests.

**Comment by flodolo** [comment]
> It has the same defect of the current solution, i.e. it's not easy to see what's in production compared to stage.

Technically, I think this can be currently done [with a 2-dots diff](https://github.com/mozilla/legal-docs/compare/prod..master). If that correct, we're still missing a few updates for #1715.

If all documents live in the same branch, we'd need some script generating and maintaining the list of differences.

**Comment by pmac** [comment]
For #1715 I was forced to simply copy all of the versions of the requested docs to a temp dir, then switch to the prod branch, and then copy the files back and commit. It's kludgy but it's the best option since attempting to cherry-pick changes via git would probably result in missed modifications in some earlier commit or said commits would contain changes to files not intended to go to prod. I proposed this solution after doing this since copying files around seems to be where we are at the moment regardless. I just thought if it didn't also involve branches that maybe others could do it as well.

**Comment by flodolo** [comment]
I agree that cherry picking doesn't work, the only way forward is copying files and syncing content, not history.

Could we use a GitHub action, manually triggered, to create a pull request against prod?

I only looked briefly, but Actions seem to [support optional inputs](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/), so you could have the action:
* Copy all documents from master to prod by default ("all").
* Copy a specific document (or documents as a comma separated list?) from master to prod.

And then create a PR against prod.

**Comment by flodolo** [comment]
Exactly. If no parameter is supplied, if would copy the whole content to prod. If a parameter is passed (as a list of file names `firefox_privacy_notice.md`), it would copy over source+translations of that file.

Not sure if we can pass only one file name, which would require multiple PRs, or a list of names. Even multiple PRs wouldn't be too bad, because they touch different files, and they shouldn't have any conflict with each other.

**Comment by pmac** [comment]
I'm exploring this now. Your existing l10n workflow is a good template for this. I hope to have something we can try soon. Thanks for the suggestion!
