### ISSUE TITLE
Lint documents for issues

### ISSUE THREAD

**Issue by flodolo** [mozilla/legal-docs#1729]
If an anchor doesn't have a space before, it will be displayed as plain text
https://github.com/mozilla/legal-docs/commit/861814aeb46b9ea2b37571c940f74f1b05808436

It might be useful to extract a list of anchors and links, and confirm that the translation has the same. This might require getting rid of obsolete versions of document, e.g. Firefox Privacy Notice is clearly unmaintained for a bunch of locales.

**Comment by flodolo** [comment]
Apparently the parser fails also if the anchor is followed by a colon, or probably any other character (I don't think Japanese was using a standard colon there)
https://github.com/mozilla/legal-docs/commit/00f9a55bae15f1a023a66986000919e0bf109e79

@pmac 
Is there any way we can fix the parser to be a little more flexible with anchors?

**Comment by flodolo** [comment]
I should have something working next week, but the picture is not great.

Example: this was never updated in localized documents, so all locales have the wrong link
https://github.com/mozilla/legal-docs/commit/e13b36c5be04a376c37929d885d9af95b26d27dc

**Comment by pmac** [comment]
> Apparently the parser fails also if the anchor is followed by a colon, or probably any other character (I don't think Japanese was using a standard colon there)

I believe these IDs in the curly braces are handled by a Markdown extension, so I guess it's parser isn't behaving properly here. I'll investigate.

**Comment by flodolo** [comment]
I have a working linter in the "linter" branch. I'll flag you as reviewer once I narrowed down the list of errors.

Mostly need @mafeld review on #1731 (which is mostly a rubber stamp), and his opinion on #1733

**Comment by flodolo** [comment]
Closed via #1739
