### ISSUE TITLE
Out of sync documents

### ISSUE THREAD

**Issue by flodolo** [mozilla/legal-docs#1733]
cc @peiying2 

While working on a linter and comparing links between reference and localized versions, I noticed a few glaring issues.

## Websites ToU

This change was never reflected in localized documents.
https://github.com/mozilla/legal-docs/commit/e13b36c5be04a376c37929d885d9af95b26d27dc

I could easily fix the link, but that won't fix the section title or the text. Should this be updated in the localized versions through the vendor, or is the link enough for now?

## Firefox Privacy Notice and Mozilla Privacy Policy

firefox_privacy_notice.md (reference: 2022-03-10)
  - bn: Outdated (2017-07-20)
  - cs: Outdated (2017-09-28)
  - el: Outdated (2017-07-20)
  - en_b: Outdated (2017-09-28)
  - hr: Outdated (2017-07-20)
  - hu: Outdated (2017-07-20)
  - mk: Outdated (2017-07-20)
  - ro: Outdated (2017-07-20)
  - sr: Outdated (2017-07-20)
  - ta: Outdated (2017-07-20)

mozilla_privacy_policy.md (reference: 2020-09-09)
  - af: Outdated (2014-04-15)
  - bg: Outdated (2018-05-25)
  - bn: Missing date
  - cs: Outdated (2018-05-25)
  - da: Outdated (2018-05-25)
  - el: Outdated (2018-05-25)
  - et: Outdated (2018-05-25)
  - fa: Outdated (2014-04-15)
  - fi: Outdated (2018-05-25)
  - he: Outdated (2014-04-15)
  - hr: Outdated (2018-05-25)
  - hu: Outdated (2018-05-25)
  - lt-LT: Outdated (2014-04-15)
  - lt-LV: Outdated (2014-04-15)
  - mk: Outdated (2018-05-25)
  - my: Outdated (2014-04-15)
  - nb-NO: Outdated (2018-05-25)
  - nl: Outdated (2018-05-25)
  - ro: Outdated (2018-05-25)
  - sk: Outdated (2018-05-25)
  - sl: Outdated (2018-05-25)
  - sr: Outdated (2018-05-25)
  - sv: Outdated (2018-05-25)
  - sw: Outdated (2014-04-15)
  - ta: Missing date
  - th: Outdated (2018-05-25)
  - tl: Outdated (2018-05-25)
  - xh: Outdated (2014-04-15)
  - zu: Outdated (2014-04-15)

Should the outdated documents be removed for good, and avoid any confusion? Some are 8 years old.

## Missing update date

Several documents don't have a last update date:
- acceptable_use_policy.md
- facebook_privacy_info.md
- firefox_about_rights.md
- firefox_lite_about_rights.md
- firefox_lite_contentservices_reward.md
- firefox_lite_contentservices_tos.md
- firefox_reality_about_rights.md
- report_infringement.md
- thunderbird_about_rights.md
- websites_tou.md

@mafeld 
Thoughts? To me, it would seem logical to remove the obsolete/unmaintained localizations.

I'm sure there are other issues hanging around, but it's hard to tell at the moment with these many errors. For example, there's a link mismatch in the Mozilla Privacy Policy for a lot of locales, but that's caused by those locales being years behind, and unmaintained.

**Comment by flodolo** [comment]
Forgot one thing: I still have no clue what's the goal of `en_b` (also cc @pmac)

**Comment by flodolo** [comment]
A few more (Firefox Lite, Common Voice)

common_voice_privacy_notice.md (reference: 2019-08-15)
  - br: Missing date
  - dv: Missing date
  - he: Outdated (2018-05-01)
  - kk: Outdated (2018-05-01)
  - mk: Outdated (2018-05-01)
  - sk: Outdated (2018-05-01)
  - sq: Outdated (2018-05-01)
common_voice_terms.md (reference: 2018-11-30)
  - dv: Missing date
  - he: Outdated (2017-06-19)
  - kk: Outdated (2018-05-01)
  - mk: Outdated (2018-05-01)
  - sk: Outdated (2018-05-01)
  - sq: Outdated (2018-05-01)
firefox_lite_privacy_notice.md (reference: 2019-12-10)
  - zh-CN: (2019-03-15)

**Comment by peiying2** [comment]
@flod, thanks for the report. 
- Based on the discussions we had back in 2019 when Jeff tried to unify the languages across the company, he asked Legal to conform to the same locale list, much smaller than the ones supported at the time. That decision dropped a lot of languages for the Common Voice related docs.
- Going back further, it was budget related decision that Legal decided to stick to the top performing Firefox Desktop locales and drop the rest. In fact, there is an English version B English (not published) used for these dropped locales so users are pointed to the English (published) version to get the latest policy.

@mafeld not sure if you were involved in all the decision making. If you remembered anything else, please chime in.

**Comment by peiying2** [comment]
Given that we don't use the Smartling platform for the legal docs so we are not bound to the list there. If there is a genuine need to open up some of the locales, we should revisit this need. @mafeld 

@flodolo let's say we keep the docs the way they are - no change. My only concerns are the links, some might be related to doc update (docs no longer exist), and others could be the change of the links. If we focus on updating the links so they don't point to 404, then that might be a short term goal to address.

**Comment by mafeld** [comment]
Sorry for the delay on this. 

We should definitely remove the one for Firefox Lite. 

As for the ones that don't have an updated date, my plan is to insert that the next time there is an update to them. 

Is it possible to see how many users we have in the various locales for the Mozilla Privacy Policy and Firefox Privacy notice to decide whether we should update the languages or consolidate to the languages we're using now?

**Comment by flodolo** [comment]
> Is it possible to see how many users we have in the various locales for the Mozilla Privacy Policy and Firefox Privacy notice to decide whether we should update the languages or consolidate to the languages we're using now?

You mean users in Firefox, or visitors on mozilla.org?

This is a [graph for all locales](https://sql.telemetry.mozilla.org/queries/85321#211215) (see also [pie chart](https://sql.telemetry.mozilla.org/queries/85321/source#211216)).

If we want to expand the list of supported locales, I would probably draw the line at Hungarian: `nl`, `cs`, `hu`. That would cover the [top 15 locales](https://sql.telemetry.mozilla.org/queries/2045#183325).

**Comment by mafeld** [comment]
I think the top 15 locales seems reasonable to me for localization of our legal docs. Is this also the at cutoff we use for other localization efforts?

**Comment by flodolo** [comment]
We use vendors for a very limited number of areas, and requesters normally ask for specific locales depending on the service (e.g. Play/App Store, or survey). We probably don't even get to top 15 locales normally.

With that, letting @peiying2 take over the conversation, because she knows more about it than me  ;-)

**Comment by mafeld** [comment]
Given that, I agree that we can limit to top 15 locales for legal docs and get rid of outdated ones that aren't within that top 15.

**Comment by flodolo** [comment]
> Given that, I agree that we can limit to top 15 locales for legal docs and get rid of outdated ones that aren't within that top 15.

I think the next steps are:
* Create a PR to remove Firefox Lite, and Firefox PN + privacy notice for locales outside of top 15.
* Get nl, cs, hu updated.

I can work on the first item this week.

**Comment by peiying2** [comment]
Want to share the list of locales we have been supporting the last few years (once the trimmed list was implemented): https://github.com/mozilla/legal-docs/blob/38c3b8417ed5b8641b818947c2c574150c82a3a8/.github/stats.json#L347 - It is the same list for Fx PN/ToS (the ones that are up to date). Mozilla.org vendor serviced locales include locales (ar, hi, id) that are not performing well according to the Telemetry report.   

Whatever is decided, let's make sure the legal docs (website PN, Fx PN/ToS, Focus PN, etc) share the same locale list.

**Comment by flodolo** [comment]
@peiying2 
If you want to start to take a look, this is a first attempt (didn't double check it). There's a lot of locales that would be removed from the list above (ar, hi, id, ko, tr, vi, zh-TW)
https://github.com/mozilla/legal-docs/pull/1738

**Comment by flodolo** [comment]
Regarding `en_b`. Looking at the commit history, this was created to have a reference for locales that are out of date, pointing people to en-US in the last paragraph.

Since we're getting rid of outdated versions, and consolidating the number of locales, should be remove that as well?

**Comment by peiying2** [comment]
> Since we're getting rid of outdated versions, and consolidating the number of locales, should we remove that as well?

A yes for me.

**Comment by flodolo** [comment]
Most of the issues were fixed in https://github.com/mozilla/legal-docs/pull/1738
