### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by flodolo** [mozilla/legal-docs#1735]
This is one of the few repositories still using a `master` branch.

@pmac 
As far as I've checked, it should be relatively quick to fix in Bedrock, and it wouldn't impact production.

Bedrock: 
* [x] Update [LEGAL_DOCS_BRANCH](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L1091) setting

This repository:
* [x] Create `main` branch
* [x] Update references in GitHub Actions

**Comment by pmac** [comment]
Sounds good. I can't think of anything else that would need updating apart from our local clones. Let's give it a go.

**Comment by flodolo** [comment]
This should be done. On to the linter now (next week though).
