### ISSUE TITLE
Legal doc cleanup audit

### ISSUE THREAD

**Issue by peiying2** [mozilla/legal-docs#1740]
@mafeld some are already in progress and the issues have been raised. This is a collection of issues that we would like to get clarification from you:

1). Common Voice locale list. They have a unique set  of languages and they have not been updated, not  through the legal repo. The production version is hosted on the CV site itself, not on Bedrock.

2). Focus PN was recently updated to the broader set of languages. We will keep them for now. Once there is a revision, you can decide to either update them all, or limit to the top 15 languages.

3). Through this audit, we identified Czech, Hungarian and Dutch as part  of the top performing markets. We need to add them to the regularly updated locale list. Could you file a Jira ticket so we can get this started so they will be on the same page as the other locales.

**Comment by flodolo** [comment]
> 2). Focus PN was recently updated to the broader set of languages. We will keep them for now. Once there is a revision, you can decide to either update them all, or limit to the top 15 languages.

The same is true for Firefox PN.

This is the list of locales that we should remove when we update those docs:
* ar
* es-MX
* hi
* ko
* tr
* vi
* zh-TW

At the moment, the translations are up to date with en-US, so no point in removing and wasting the work already done.

**Comment by flodolo** [comment]
> 3). Through this audit, we identified Czech, Hungarian and Dutch as part of the top performing markets. We need to add them to the regularly updated locale list. Could you file a Jira ticket so we can get this started so they will be on the same page as the other locales.

Dutch already has Firefox PN up to date.

firefox_privacy_notice: cs, hu
mozilla_privacy_policy: cs, hu, nl

P.S. I'm going to close the other issue, and keep this one around.

**Comment by flodolo** [comment]
> 1). Common Voice locale list. They have a unique set of languages and they have not been updated, not through the legal repo. The production version is hosted on the CV site itself, not on Bedrock.

I've tried to look through the history of those documents. As far as I can tell, they were delivered through HTP ([example](https://github.com/mozilla/legal-docs/pull/1461)).

I fixed 3 errors in those files (br, dv), which results in only a handful of locales being actually outdated: he, kk, mk, sk, sq. What they are missing are:
* https://github.com/mozilla/legal-docs/commit/ff6de2ec8defccb6ff5395d04366368abb1c2c45
* https://github.com/mozilla/legal-docs/commit/c4d9b3647155de1efafdc29fa6d157679b7ce74c

They should be either updated — if we consider Common Voice an exception to our list of supported locales, and it's a requirement to have all PN translated — or removed.

What surprises me is that, as far as I know, we haven't added a single new language in 2+ years to these legal translations, while CV definitely added new languages. That feels like this part of the process is not really owned by CV.

**Comment by flodolo** [comment]
BTW, worth double checking: do we still have [Firefox OS privacy notice](https://www.mozilla.org/en-US/privacy/firefox-os/) because of legal commitments?

**Comment by mafeld** [comment]
I will put this comment in a more recent legal localization issue as well (sorry for the delay).

1. Firefox OS - we can remove the Firefox OS privacy notice and put it in the archive (https://www.mozilla.org/en-US/privacy/archive/)
2. Common Voice is an exception to the language we choose to localize in because of the nature of the product  and the way they select languages to focus on. Let's keep it as is until we do another update and we can decide then. 
3. Agreed on Focus. Let's leave for now and update to the same languages as Firefox on next update.

**Comment by flodolo** [comment]
There are 2 files in the root of the repository
* UP_research_addon_privacy_notice.md
* heartbleed_privacy_notice_en.US.md

They're clearly unused on mozilla.org, and very old. Can they be removed?

**Comment by mafeld** [comment]
yes. We can remove these.

**Comment by flodolo** [comment]
Only open question is CV, and we'll look into it when the document needs to be udpated.
