### ISSUE TITLE
Archive Firefox OS privacy notice

### ISSUE THREAD

**Issue by flodolo** [mozilla/legal-docs#1746]
From @mafeld in [this comment](https://github.com/mozilla/legal-docs/issues/1740#issuecomment-1121516857)

> Firefox OS - we can remove the Firefox OS privacy notice and put it in the archive (https://www.mozilla.org/en-US/privacy/archive/)

Does it mean that we can drop the localized versions, and only keep the English one as an archived version?

@pmac 

How would this work? Looks like the [privacy/archive](https://github.com/mozilla/bedrock/tree/main/bedrock/privacy/templates/privacy/archive) is made of static HTML files. 
* Should just file an issue on Bedrock to get the en-US privacy converted to HTML and then remove the files here?
* Is there anything else to do? The notice is currently displayed [here](https://github.com/mozilla/bedrock/tree/main/bedrock/privacy/templates/privacy/archive), and there's a sidebar link.

**Comment by pmac** [comment]
Hmm... it would be a bit of work to convert it to static and move the URL. Is there any harm in just leaving it as is but removing the side-bar link?

**Comment by mafeld** [comment]
yes we can drop the localized versions. 

And yes, it's ok to leaving the URL as is, remove the side-bar link, and add Firefox OS to the page labeled outdated policies. (https://www.mozilla.org/en-US/privacy/archive/)

let me know if I should help with that page.

**Comment by flodolo** [comment]
OK. I'm going to remove the localized versions for now, since most of them are outdated anyway and it doesn't have any effect to bedrock.

@pmac 
Leaving the other part of the conversation to you at this point ;-)

**Comment by flodolo** [comment]
> OK. I'm going to remove the localized versions for now, since most of them are outdated anyway and it doesn't have any effect to bedrock.

This was done in https://github.com/mozilla/legal-docs/pull/1747 (only dev for now)

One positive is that we also removed a bunch of folders/locales that were only used by Firefox OS: af, bg, da, fi, lt-LT, lt-LV, my, nb-NO, xh, zu

**Comment by pmac** [comment]
Thanks. I'll file an issue in bedrock to make the changes there.

**Comment by pmac** [comment]
In the bedrock work for this we decided to go ahead and fully archive the Firefox OS doc and redirect the old URL. So we also no longer need to keep the English version of the doc in this repo once the changes go to production, which should be early next week.
