### ISSUE TITLE
Create websites for Hubs Privacy Notice and Terms

### ISSUE THREAD

**Issue by mafeld** [mozilla/legal-docs#1763]
Hi @pmac and @alexgibson, 

For a long time, the Hubs Privacy Notice and Terms of Service have lived in Github. I think the time has come that they have their own full website pages like our other products. 

Could you please create URLs for the Hubs Privacy Notice and Terms. It doesn't need to be exactly these URLs, but my suggestions would be: 
https://www.mozilla.org/privacy/hubs/
https://www.mozilla.org/about/legal/terms/hubs/

Then can we put the content from the following two Github files on those URLs?
https://github.com/mozilla/legal-docs/blob/main/en/mozilla_hubs_tos.md
https://github.com/mozilla/legal-docs/blob/main/en/mozilla_hubs_privacy_notice.md

**Comment by pmac** [comment]
Sure thing. Do you know if there's a particular logo we should use on the pages?

**Comment by mafeld** [comment]
@misslivirose - Could you answer what logo should be on the Privacy Notice for Hubs?

**Comment by misslivirose** [comment]
![Black_Logo_Hubs](https://user-images.githubusercontent.com/4313320/171520741-7ef67f7f-1d5a-4a1f-9fb5-0e9585b0ad87.png)
![White_Logo_Hubs](https://user-images.githubusercontent.com/4313320/171520742-49fac3a1-c12f-48e9-ad96-bde1b53a53af.png)

**Comment by stevejalim** [comment]
The changes have been merged. I don't have access to trigger a prod release of those files, but I'll arrange it

**Comment by stevejalim** [comment]
Updated files are now in the [prod branch of legal-docs](https://github.com/mozilla/legal-docs/pull/1771), so will go live with the next Bedrock release.

Also, dev currently shows the files:
* https://www-dev.allizom.org/en-US/privacy/hubs/
* https://www-dev.allizom.org/en-US/about/legal/terms/hubs/

**Comment by stevejalim** [comment]
@mafeld These are now live on 

* https://www.mozilla.org/en-US/privacy/hubs/
* https://www.mozilla.org/en-US/about/legal/terms/hubs/

If you're happy, please close this issue and I'll let the Hubs team know they should start linking to these pages instead of Github

**Comment by flodolo** [comment]
This looks fixed 👍🏼
