### ISSUE TITLE
Hubs ToS page has two broken links to Hubs privacy policy

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/legal-docs#1835]
https://www.mozilla.org/en-US/about/legal/terms/hubs/

There are two links to the Hubs privacy policy in the section "2. Communications and Content" that leads to a 404 page (https://www.mozilla.org/privacy/hubs-subscription/).

**Comment by peiying2** [comment]
> https://www.mozilla.org/en-US/about/legal/terms/hubs/
> 
> There are two links to the Hubs privacy policy in the section "2. Communications and Content" that leads to a 404 page (https://www.mozilla.org/privacy/hubs-subscription/).

Where do you see the above link? The correct one should be https://www.mozilla.org/en-US/privacy/hubs/

**Comment by flodolo** [comment]
He provided the page were those links in the comment (section 2 of the Terms page).

Looking into it.
