### ISSUE TITLE
Pocket legal docs have some minor issues

### ISSUE THREAD

**Issue by peiying2** [mozilla/legal-docs#1848]
_ToS_:

**Current**: This is in the first paragraph `… licensed by Mozilla Corporation. (referred to herein as "we," "us," "our," "Mozilla") and …`.  The period after Mozilla Corporation should be removed.
**Correction**: `…Mozilla Corporation (referred to herein as "we,"…`

**Current**: This is in "row 108" where the paragraph starts with `To initiate an arbitration proceeding, …` there are two phone numbers listed, but the format is inconsistent. Most importantly, it needs to add a country code to the phone number `… by calling 800.352.5267.`  
**Correction**: `1-800-352-5267`

_PP_:
**Current**: This is in row 115 under the Amendments to Privacy section. This is the last sentence of the paragraph `… application or thirty (30) after the terms are changed …`. The word `days` is missing.
**Correction**: `… application or thirty (30) days after the terms are changed …`.

**Comment by peiying2** [comment]
@mafeld please address the issues the vendor raised.

**Comment by mafeld** [comment]
all 3 of these corrections are fine. Thank you for spotting them. I agree with your proposed fixes.

**Comment by peiying2** [comment]
> all 3 of these corrections are fine. Thank you for spotting them. I agree with your proposed fixes.

@mafeld could you make the edits in English so I can approve them before we take over the l10n side. 

Do let me know if you have other request(s) before the end of the year so I can lump them together to help minimize fees in some locales. Thanks.

**Comment by mafeld** [comment]
done
