### ISSUE TITLE
Typo on privacy page

### ISSUE THREAD

**Issue by stevejalim** [mozilla/legal-docs#1864]
Originally from https://github.com/mozilla/bedrock/issues/12616

> https://www.mozilla.org/en-US/privacy/ should read "if it is up to date", missing the word "it", in this bullet

> we collect it automatically through our products and services (e.g., when your Firefox browser checks with us to see if is up to date);

See https://github.com/mozilla/legal-docs/blob/d293203658efbda85912913b446f6c35749cbf5f/en/mozilla_privacy_policy.md?plain=1#L21

**Comment by mafeld** [comment]
I will create a pull request for that change. Thank you.
