### ISSUE TITLE
A few broken links in the en/*.md docs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/legal-docs#1876]
I cleaned up a bunch of the verbose output, but here's a summary of the three broken links.

- https://aim.yahoo.com/aim/us/en/optout/
- https://affiliates.mozilla.org/fb/faq
- https://www.ftc.gov/privacy/coppafaqs.shtm

```sh
find en -name \*.md -print0 | xargs -0 -n1 npx markdown-link-check

FILE: en/websites_privacy_notice.md
  [✖] https://aim.yahoo.com/aim/us/en/optout/
  24 links checked.

  ERROR: 1 dead links found!
  [✖] https://aim.yahoo.com/aim/us/en/optout/ → Status: 0

FILE: en/facebook_privacy_info.md
  [✖] https://affiliates.mozilla.org/fb/faq
  2 links checked.

  ERROR: 1 dead links found!
  [✖] https://affiliates.mozilla.org/fb/faq → Status: 0

FILE: en/pocket_tos.md
  [✖] https://www.ftc.gov/privacy/coppafaqs.shtm
  35 links checked.

  ERROR: 29 dead links found!
  [✖] https://www.ftc.gov/privacy/coppafaqs.shtm → Status: 404
```

**Comment by mafeld** [comment]
We no longer use Yahoo, I have submitted a PR to fix that disclosure
https://github.com/mozilla/legal-docs/pull/1878/commits/3d33e5b519bd87af764e61e97b6a5a1401dd6629

We no longer need the Facebook Privacy Info page. We should move it to archive. 

I have submitted a PR to fix the COPPA link on the Pocket page:
https://github.com/mozilla/legal-docs/pull/1877/commits/0db22104771cf754ad9a49ab54bfa94279d632fa

**Comment by flodolo** [comment]
> We no longer need the Facebook Privacy Info page. We should move it to archive.

You mean remove the file, or is there an archive of legal docs on mozilla.org

**Comment by mafeld** [comment]
There's an outdated policies page: https://www.mozilla.org/en-US/privacy/archive/

**Comment by flodolo** [comment]
> There's an outdated policies page: https://www.mozilla.org/en-US/privacy/archive/

Then I think we need something on the Bedrock's side to make it happen.

@pmac or @alexgibson 
I can't find [this page](https://github.com/mozilla/legal-docs/blob/main/en/facebook_privacy_info.md) on mozilla.org. How do we make it show up in [archive](https://www.mozilla.org/en-US/privacy/archive/)?

**Comment by pdehaan** [comment]
@flodolo Maybe this? https://www.mozilla.org/en-US/privacy/facebook/
via https://github.com/mozilla/bedrock/blob/179843ad49a66929730507d76058e23c9ada734f/bedrock/privacy/views.py#L71-L72

Although I can't seem to find where it's linked from. I just guessed at the URL based off the Thunderbird URLs.

**Comment by alexgibson** [comment]
I think it's this one: https://www.mozilla.org/en-US/privacy/facebook/

Not all policies are linked via the index, but I'm not sure why to be honest. I think legal might sometimes say not to, but the reason why I'm not 100% sure (I could also be wrong here).

**Comment by peiying2** [comment]
@mafeld please address the issues raised so this can be fixed.

**Comment by flodolo** [comment]
> We no longer need the Facebook Privacy Info page. We should move it to archive.

This is the only issue remaining, and should be fixed on Bedrock's side first.
https://github.com/mozilla/legal-docs/pull/1877
https://github.com/mozilla/legal-docs/pull/1878

**Comment by mafeld** [comment]
Does that mean I need to push to bedrock first, or are we waiting on something from the websites team?

**Comment by flodolo** [comment]
The bedrock teams need to make changes to move that document to archive, there's nothing to do on this side. It's unclear to me if someone filed an issue already, in which case we could close this.

**Comment by alexgibson** [comment]
Filed https://github.com/mozilla/bedrock/issues/12935 to archive the privacy notice.

**Comment by flodolo** [comment]
Thanks Alex, I'm going to close this one, since all the rest is fixed (and the link for the archived page will remain as is).
