### ISSUE TITLE
Update accounts link in MDN privacy

### ISSUE THREAD

**Issue by janbrasna** [mozilla/legal-docs#2134]
[`mdn_plus_privacy.md#information-we-collect`](https://github.com/mozilla/legal-docs/blob/dd18d74869a55878258673175df0bd397faeb135/en/mdn_plus_privacy.md#information-we-collect--infowecollect-) links to https://www.mozilla.org/privacy/firefox/#firefox-accounts-join-firefox that no longer exists.

The new location might be https://www.mozilla.org/privacy/mozilla-accounts/ that's also used for this context elsewhere.

**Comment by mafeld** [comment]
Yes. This is the correct new link. Thank you for catching it. Go ahead and make the change.

**Comment by flodolo** [comment]
Looks like the first link is used also in VPN and Relay private notices. I'll update all of them.
