### ISSUE TITLE
A wrong bullet character in the Acceptable Use Policy

### ISSUE THREAD

**Issue by aleksejrs** [mozilla/legal-docs#339]
In https://raw.githubusercontent.com/mozilla/legal-docs/master/acceptable_use_policy/en-US.md, the "Collect or harvest personally identifiable information" item begins with a "`•`" instead of "`*`" or "    *", so in https://www.mozilla.org/en-US/about/legal/acceptable-use/ it is rendered as a continuation of the previous line.

**Comment by pdehaan** [comment]
See #340. Good catch! It looks like it was incorrect in almost all the locales.
