### ISSUE TITLE
German translation for firefox_cloud_services_PrivacyNotice is confusing

### ISSUE THREAD

**Issue by vladikoff** [mozilla/legal-docs#410]
![](http://v14d.com/i/5617d1a8217c7.jpg)

> Left ENGLISH | Right GERMAN "Google Translated"

Ref: https://www.reddit.com/r/firefox/comments/3o34o2/questions_indepth_security_consideration_of_the/?ref=share&ref_source=link

> The german version of https://accounts.firefox.com/legal/privacy states "Wenn Sie sich für ein Konto registrieren, erhalten wir Ihre E-Mail-Adresse und Ihr Passwort." saying Firefox will get my email & password in plain text.. This would render the whole security design worthless?!
### STR

Visit https://accounts.firefox.com/de-de/legal/privacy
### Expected

Expected translation should be `we receive your email address and a hash of your password.`
### Actual

`we receive your email address and your password.`

**Comment by mozcmcgill** [comment]
The localization team has edited the text in the German Privacy Notice to make it clear that we don't receive the password but the hash of it. Thank you for bringing this to our attention!

**Comment by peiying2** [comment]
Actually en-US was updated from the old to the new text in July but this was not communicated.  The change needs to happen to all the impacted locales. I have filed a bug on this.  https://bugzilla.mozilla.org/show_bug.cgi?id=1213392
