### ISSUE TITLE
Push WebRTC/Hello into production for Romanian locale

### ISSUE THREAD

**Issue by cristisilaghi** [mozilla/legal-docs#450]
Translations are already done on Github.
Can you please push them into production? :)

**Comment by kyoshino** [comment]
Sent https://github.com/mozilla/bedrock/pull/3452 to push the latest changes to production.

**Comment by cristisilaghi** [comment]
Also, just saw that legal docs for "Firefox Cloud Services" are outdated for Romanian locale.

We need latest revision of file(s) pushed for https://accounts.firefox.com/legal/privacy

**Comment by MikkCZ** [comment]
@cristisilaghi Is this still an issue (I hope it's not two years after).

**Comment by cristisilaghi** [comment]
Nope. Thanks for reminding me to close this :)
