### ISSUE TITLE
Need a better way to push changes to production

### ISSUE THREAD

**Issue by kyoshino** [mozilla/legal-docs#451]
Currently those sites have the docs as static pages, but looks like none of them are automatically updated. We have to talk to each team to always serve the latest docs:
### www.mozilla.org
- https://www.mozilla.org/en-US/privacy/
- https://www.mozilla.org/en-US/about/legal/
- manually syncing as Git submodule: https://github.com/mozilla/bedrock/tree/master/vendor-local/src
### accounts.firefox.com
- https://accounts.firefox.com/legal/privacy
- https://accounts.firefox.com/legal/terms
- specified at: https://github.com/mozilla/fxa-content-server/blob/master/bower.json#L36
### marketplace.firefox.com
- https://marketplace.firefox.com/privacy-policy
- https://marketplace.firefox.com/terms-of-use
- manually syncing: https://github.com/mozilla/zamboni/tree/master/media/docs

**Comment by rfk** [comment]
> but looks like none of them are automatically updated

Accounts *should* be picking up updates automatically, but deploy on a two-week cycle so there could be up to a two-week delay between changes landing in this repo, and changes going out to production.

So, two questions from the accounts side of things:

* Are there changes older than two weeks that have not made it into production on accounts.firefox.com?  If so then there's likely a bug in way we're handling the updates.
* Is our two week cycle too slow for legal doc updates?  If so then we'll have to figure out a way to trigger new builds and deploys when legal docs change.

**Comment by peiying2** [comment]
@rfk, at this point, most likely the changes were more than 2 weeks old.  I don't think firefox account legal docs get updated often. Unless it's urgent, we let it wait until its natural update cycle take place. If it is urgent, we can file a bug.

**Comment by rfk** [comment]
OK, sounds good, thanks.

**Comment by MikkCZ** [comment]
@kyoshino Is there still a project where updates need to be done manually?

**Comment by kyoshino** [comment]
www.mozilla.org is still doing this manually.
https://github.com/mozilla/bedrock/commits/master/vendor-local/src

**Comment by MikkCZ** [comment]
If it's about just updating a submodule, I guess that could be easily solved by updating it before deploy on their side.

**Comment by kyoshino** [comment]
See also: [Bug 1145216](https://bugzilla.mozilla.org/show_bug.cgi?id=1145216)

**Comment by pmac** [comment]
I've finally made some progress on this!

https://github.com/mozilla/bedrock/pull/9213

This will load the docs into bedrock's database every few minutes, so changes will be reflected without the need of any websites team intervention or a deployment. The catch is that any mistake will cause the page to either break the layout or even throw an error. I'm wondering if the team would be okay with having changes in the `master` branch only show up automatically on https://www-dev.allizom.org for verification, and then once you're happy with how it looks there you can push the master branch to a `prod` branch that would cause the changes to show up on https://www.mozilla.org. Is that something that the team would be willing to do? The git command is pretty easy. When you're happy with the state of things in the master branch you just:

```bash
git push origin master:prod
```

That will cause your local master branch to be pushed to your remote called `origin` as the `prod` branch.

**Comment by pmac** [comment]
@peiying2 any thoughts on the above proposal for a `prod` branch? The PR in bedrock has preliminary approval, but I want to get buy in from the people managing this repo before we merge that change.

**Comment by peiying2** [comment]
> @peiying2 any thoughts on the above proposal for a `prod` branch? The PR in bedrock has preliminary approval, but I want to get buy in from the people managing this repo before we merge that change.

This sounds like a great idea, like what I used to do for mozillo.org web site. I am good with this. I think we may need some configuration on our local machine to make the push from master to prod? I did it through VMWare. Not sure how this is done directly here. It will be better if one of the legal team contributors share this responsibility. You can walk us through how this is done.

**Comment by pmac** [comment]
> You can walk us through how this is done.

I would be happy to.

**Comment by pmac** [comment]
I've gone ahead and created the [prod branch](https://github.com/mozilla/legal-docs/tree/prod) so that it is up-to-date with the current `master` branch. I can explain pushing updates to prod when you're ready, but it will depend on what tools you use to interact with git and GitHub.

**Comment by peiying2** [comment]
@pmac I have invited Legal team to the training session with you. Let me know if the current time slot works.

**Comment by peiying2** [comment]
This was done and it works like a charm! Thanks for the training and for updating the readme.
