### ISSUE TITLE
https://www.mozilla.org/en-US/privacy/firefox-cloud/ is now 404.

### ISSUE THREAD

**Issue by jrgm** [mozilla/legal-docs#672]
Multiple documents in this repo (e.g., https://github.com/mozilla/legal-docs/blob/master/firefox_cloud_services_ToS/en-US.md) link to https://www.mozilla.org/en-US/privacy/firefox-cloud/. 

But that URL is now returning a 404.

**Comment by kyoshino** [comment]
This has been solved in https://github.com/mozilla/bedrock/pull/4275.

**Comment by eleemoz** [comment]
Thank you, @kyoshino!

**Comment by jrgm** [comment]
Closing, per above.
