### ISSUE TITLE
404 Telemetry link in Firefox Privacy Notice

### ISSUE THREAD

**Issue by alexgibson** [mozilla/legal-docs#886]
In: ` legal-docs/firefox_privacy_notice/en-US.md` (and other translations)

404: https://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/index.html

Looks like it has moved to: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/index.html

**Comment by eleemoz** [comment]
This is being fixed with the Firefox 56 update. #887
