### ISSUE TITLE
Outdated information on addons pane

### ISSUE THREAD

**Issue by rugk** [mozilla/legal-docs#949]
In the (from the privacy policy linked) site https://blog.mozilla.org/addons/how-to-opt-out-of-add-on-metadata-updates/:
> The add-on identifiers are used to […], as well as in aggregate to provide personalized recommendations in the Get Add-ons pane of the Add-ons Manager.

In old Firefox version there was "Recommended for you" part. This is not there anymore. Also AFAIK the `about:add-ons` page is not personalized anymore. Or is it?

If so I think that should be mentioned in the main privacy policy as it is analyzing data for one personal user and thus not only technical.
Also IMHO one should be able to disable the personalisation of the data while still getting automated add-on updates.

**Comment by eleemoz** [comment]
> Also AFAIK the `about:add-ons` page is not personalized anymore. Or is it?

That's correct, except when we adjust content client-side based on things like whether an add-on is already installed, which does not involve sending any information about your add-ons to us.

> If so I think that should be mentioned in the main privacy policy as it is analyzing data for one personal user and thus not only technical.

If Firefox does bring back personalized recommendations for addons, we'd probably cover that under "Suggest Relevant Content".  In the meantime, I've put in a request to have the blog post information updated. Thanks for pointing out the outdated info!
