### ISSUE TITLE
You explain what, how and when, but sometimes not "why"…

### ISSUE THREAD

**Issue by rugk** [mozilla/legal-docs#950]
In your privacy policy you are great at explaining how and when you collect data, but sometimes you miss the "why" at all you collect this type of data. (And no, I don't mean the general statement: "to improve our services")

Which was striking to me was the example is e.g. why my mail address is sent to "SalesForce Marketing Cloud" when using Firefox accounts? Why do you send data to advertising companies?

**Comment by peiying2** [comment]
@mafeld you and mika can decide if this is something to be included in the future. Otherwise, we should close the bug.

**Comment by flodolo** [comment]
Given how old this issue is and the lack of activity, I'm going to close it.
